name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test notice
        run: |
          VERSION_NAME="$(git describe --match build --dirty)"
          echo $VERSION_NAME
          echo "::notice::Published $VERSION_NAME"
